### ISSUE TITLE
Enable multiple JMX end points to be supported

### ISSUE THREAD

**Issue by guyhoskinsibm** [IBMStreams/streamsx.jmxclients#19]
Allow multiple JMX end points to be provided to the application. 
When connecting to the JMX, round robin through the multiple endpoints when the connection is lost or cannot be established. 
This would be useful for situations where Streams moves the JMX to another host if a the original host is lost.

**Comment by bmwilli** [comment]
Working on solution that would allow the jmx connection parameter to be a comma-separated list:
service:jmx:jmxmp://hoost1:9975,service:jmx:jmxmp://host2:9975.

**Comment by bmwilli** [comment]
Deploying to master for testing on a larger scale

**Comment by bmwilli** [comment]
Created release 1.3.0 of streams-metric-exporter for this.
