### ISSUE TITLE
Handle multiple instances

### ISSUE THREAD

**Issue by bmwilli** [IBMStreams/streamsx.jmxclients#5]
Currently, it requires a separate instantiation of the program for each instance you want to monitor.  A proposal was made to allow it to handle multiple instances.

Questions:
1) What should the current /prometheus endpoint do?  return all metrics for all instances?
2) Should there be a way to query/scrape just a single instance?  (e.g. /prometheus/devInstance vs /prometheus/prodInstance)
3) Would using a parameter be better (e.g. /prometheus?instancename=devInstance)
4) Should configuration allow you to choose the instances you want exposed.

**Comment by ben-dev314** [comment]
1. All metrics would be good, it might have problems if there are lots of metrics though? I've seen it crash sometimes when an instance has 200,000+ metrics
2. That would be useful too!
3. No preference
4. That would be a good feature too.

**Comment by bmwilli** [comment]
Good to know about the crash with 200,000+ metrics.  Do you remember what went wrong?  memory?

I had thought about adding the ability to filter the metrics.  Looking into the best way to do that.  In other words, what format for a configuration file to put in the filters makes the most sense and is intuitive.

**Comment by bmwilli** [comment]
Closing as version 0.9.5 handles multiple instances.  Some of the ideas shared above have not been implemented, so need to open new issues to capture those if they would be useful.
