### ISSUE TITLE
Sometimes misses jobs

### ISSUE THREAD

**Issue by ben-dev314** [IBMStreams/streamsx.jmxclients#7]
I've seen the exporter sometimes miss jobs being submitted. It logs that it has received metrics for an unknown job. Would it be possible to periodically (or when it receives metrics from an unrecognised job) update the job list?

**Comment by bmwilli** [comment]
Thanks Ben.  Yes, I believe as part of a the next upgrade, I am going to move away from using job notifications and job beans and just use the metricssnapshot and jobsnapshots to drive the job list.  That way it is much less likely to miss anything.  In addition handle multiple instances.  Thanks for the report!!

BTW Are you using this for the prometheus endpoint or the other rest endpoints or both?  Just curious.

**Comment by ben-dev314** [comment]
Currently we're just using the prometheus endpoint, it's giving us some great views on how the Streams jobs are performing 👍

**Comment by bmwilli** [comment]
Version 0.9.5 addresses this issue
